---
title: "Shiny with Megsie Siple"
author: "Danielle Barnas"
date: "4/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

Git count with Megsie: 3 (ghibli)  

## Shiny

Shiny writes html, so looks like a normal website, but also links to a bunch of a stuff happening behind the scenes:  
- R code  
- Data  
- Generating reports  

When the user changes something in the user interface, all of those things happen, and then the products of the code, data, and report generation are shown on the interface.  

## When is Shiny useful?
When we want to make R code accessible outisde of an R or RStudio environment.  
- teaching a package (eg learnR)  
- showing data visualizations to non-experts  
- steamlining certain code-intensive things (like database queries or visualizing bulky siulation outputs)  

## Shiny basics

### Starting a new Shiny app
1. install shiny  
1. New file > Shiny Web App  
1. Name your application  
1. Single vs Multiple file doesn't really matter. Stylistic choice  
1. You get a template function that already works as an app  
1. Run App up at the top of RStudio shows your app  
1. Now it's just a matter of changing inputs and outputs until you get what you want  


### Each shiny app has two components

### ui.R/server.R

- ui (user interface) object dictates the appearance of the app. UI functions write HTML.  
  - displays objects in a layout we specify  
- server() function contains rendering expressions that create the objects to display  
- both are passed to the shiny app function to create the shiny interface  

**UI**  
UI type  
- fluidPage() puts elements in rows that can include columns  
- navbarPage() has a navigation bar  

Layout Elements  
- sidebarLayout() etc  

Theme Information  
- eg shinythemes  

Output objects  
- eg plotOutput()  

Input objects  
- sliderInput()  
- fileInput()  
- etc  
- also called "widgets"  

**Server**  
- Runs R code, mainly, within functions  
- Creates objects that are linked to the UI by their tags.  
- You can lots of stuff in the server that doesn't need to be called in the UI, but can't have anything in the UI that isn't in the server  

Whats in the server  
- Rendering functions  
  - build a new object to display every time the inputs change  
- Reactive expressions  
  - reactive(): you can create an object that you can access later (unlike R, shiny doesn't store objects that have been run if they aren't defined here)  
  - eventReactive() creates reactive objects but only when a specific input changes (eg when the 'run analysis' button is clicked)  
  - 'lazy': wait until the user says "do this!" and then they do it  
- Observe expressions: change the ui based on input  
  - autopopulate default values in a form if a user has selected a default  
  - change the range for on einput based on another input  
  - 'eager': always running and evaluating when anything changes  
  
  
## Example with 01_basics
- Using a .RData file, but could also use a .csv or .txt  
- Reactive objects are not 'output' objects, so you don't need to put output$rdogs <- reactive() and you can just put rdogs <- reactive()  


## Leaflet: Maps in Shiny
- open-source javascript library that makes interactive maps  
- integrates well with Markdown files and shiny apps so you can show spatial data  
- gets complicated fast  

[Leaflet map theme link](https://leaflet-extras.github.io/leaflet-providers/preview/)  


## Shiny Dashboard

### Why make a dashboard

- Communicate data in a polished way  
- offer access to visualizations from a database  
- showing a "data story" in a linear way  


## Anatomy of a dashboard

- a dashboardPage requires three components: a header, a sidebar, and a body  

ui <- dashboardPage(  
  dashboardHeader(),  
  dashboardSidebar(),  
  dashboardBody()  
)  

- You can populate these with shiny-esque items (e.g., PlotOutput) or items unique to shinydashboard  

## Special widgets for dashboards

Dashboards have lots of fun menus  
- Notification menus (containing notificationItem() s)  
- Task menus (containing taskItem() s)  
- Sidebar menus (containing menuItem()s)  


Can load value box icons through packages, like color palettes  
- google 'packages with widgets'  
- htmlwidgets  
  - https://www.htmlwidgets.org/  
  
You can put chunks of raw html code into your shiny app.  If there's a chunk from another website you want to include, that's doable if you know a bit of basic html (so you know how to grab the chunk you want)  

## Example Dashboards
[Corona dashboard](https://sebastianwolf.shinyapps.io/Corona-Shiny/)  

[https://gadenbuie.shinyapps.io/tweet-conf-dash/?_ga=2.179585184.548717947.1617815748-132223867.1526660673](https://gadenbuie.shinyapps.io/tweet-conf-dash/?_ga=2.179585184.548717947.1617815748-132223867.1526660673)  

[https://blog.rstudio.com/2020/09/04/3-fun-shiny-apps-for-your-long-labor-day-weekend/](https://blog.rstudio.com/2020/09/04/3-fun-shiny-apps-for-your-long-labor-day-weekend/)  

[https://msiple.shinyapps.io/NovelGazingApp/](https://msiple.shinyapps.io/NovelGazingApp/)  

## Megsie GitHub Repo

[Marine Mammals](https://github.com/mcsiple/mmrefpoints)  
- R package that encloses the app  







